POST http://localhost:8080/api/mqtt/test/publish/simple
Content-Type: application/json

{}

###
POST http://localhost:8080/api/mqtt/protobuf/publish/data/BMS001
Content-Type: application/json

 {
  "terminalId": "PROTO_TERM001",
   "voltage": 13.2,
   "current": 8.5,
   "temperature": 28.5,
   "batteryLevel": 92,
   "status": "NORMAL"
 }

