POST http://localhost:8080/api/mqtt/test/publish/simple
Content-Type: application/json

{}

###
POST http://localhost:8080/api/mqtt/protobuf/publish/data
Content-Type: application/json

{
  "latitude": 37.5665,
  "longitude": 126.978,
  "heading": 90.5,
  "altitude": 35.0,
  "speed": {
    "value": 60.55
  },
  "occurAt": "2025-06-27T07:20:00Z",
  "routeDirOd": "UPLINE",
  "lastStopId": {
    "value": "12345"
  },
  "lastStopSeq": {
    "value": 5
  },
  "lastStopDist": 150,
  "originAccumDist": 2500
}

