spring:
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:h2:mem:bmsdb;DB_CLOSE_DELAY=-1
      username: sa
      password:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 3000
  application:
    name: mqtt-processor-app
  config:
    activate:
      on-profile: local
    import: classpath:yaml/log/application-local-log.yml
  h2:
    console:
      enabled: true
      path: /h2-console

mqtt:
  uri: tcp://localhost:1883
  client-id: bms-subscriber
  username: mqtt_user
  password: mqtt_password
  clean-session: false

logging:
  level:
    tmoney.gbi.bms: DEBUG
    org.springframework.integration: DEBUG
    org.eclipse.paho: INFO

mybatis:
  options:
    configuration:
      map-underscore-to-camel-case: true
      JDBCType-for-null: 'NULL'
      use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: tmoney.gbi.bms.domain
