spring:
#  datasource:
#    hikari:
#      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:mem:bmsdb;DB_CLOSE_DELAY=-1
#      username: sa
#      password:
  application:
    name: bms-mqtt-processor-app
  config:
    activate:
      on-profile: local

mqtt:
  uri: tcp://localhost:1883
  client-id: bms-subscriber-
  username: mqtt_user
  password: mqtt_password

logging:
  level:
    tmoney.gbi.bms: DEBUG
    org.springframework.integration: DEBUG
    org.eclipse.paho: INFO

